
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox VBoxMain;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Button buttonAdelante;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView textview1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.VBoxMain = new global::Gtk.VBox ();
		this.VBoxMain.Name = "VBoxMain";
		this.VBoxMain.Spacing = 6;
		// Container child VBoxMain.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonAdelante = new global::Gtk.Button ();
		this.buttonAdelante.CanFocus = true;
		this.buttonAdelante.Name = "buttonAdelante";
		this.buttonAdelante.UseStock = true;
		this.buttonAdelante.UseUnderline = true;
		this.buttonAdelante.Label = "gtk-go-forward";
		this.hbox1.Add (this.buttonAdelante);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonAdelante]));
		w1.Position = 2;
		w1.Expand = false;
		w1.Fill = false;
		this.VBoxMain.Add (this.hbox1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.VBoxMain [this.hbox1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child VBoxMain.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.GtkScrolledWindow.Add (this.textview1);
		this.VBoxMain.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.VBoxMain [this.GtkScrolledWindow]));
		w4.Position = 2;
		this.Add (this.VBoxMain);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
